name: 'Git Glean'
description: 'Automatically generate files with Git forges info'
inputs:
  username:
    description: 'Username to use in GitHub API requests'
    required: true
    default: ${{ github.actor }}
  output-path:
    description: 'Path to output file'
    required: true
  template-path:
    description: 'Path to template file'
    required: true
  format:
    description: 'Export format (md, org)'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - run: go version
      shell: bash
    - run: cd ${{ github.action_path }} && go mod download
      shell: bash
    - run: cd ${{ github.action_path }} && go run main.go --name ${{ inputs.username }} --template ${{ inputs.template-path }} --output ${{ inputs.output-path }} --format ${{ inputs.format }}
      shell: bash
